# https://www.playframework.com/documentation/latest/Configuration
include "application.local.conf"

# MongoDB Configuration
mongodb.uri = "mongodb://USERNAME:PASSWORD@localhost:27017/gardening-dashboard"

# Allow override with environment variable in production
mongodb.uri = ${?MONGODB_URI}

